### ISSUE TITLE
Build Out UI for General & Shared Views

### ISSUE THREAD

**Issue by msarit** [OurTimeForTech/shiftwork2#10]
Breaking Home Page UI Tasks Down:
- [x] Step 1: Code the NavBar
- [x] Step 2: Code the Home Page 
- [x] Step 3: Code all Button
- [x] Step 4: Code the Login Form 
- [x] ~Step 4: Code form error messages (Form fields that produce errors are reloaded encased in a div with class "field_with_errors")~
- [ ] Step 5: Polish the styles, add even padding, align headings and buttons in a similar manner throughout the App
- [x] Step 6: Matching the shifts' drop shift button style in the workers view

**Comment by saradotlog** [comment]
Might be a solution for step 4: (Needs discussing)
See https://stackoverflow.com/questions/5267998/rails-3-field-with-errors-wrapper-changes-the-page-appearance-how-to-avoid-t
if we add
```
ActionView::Base.field_error_proc = Proc.new do |html_tag, instance|
  class_attr_index = html_tag.index 'class="'
  if class_attr_index
    html_tag.insert class_attr_index+7, 'error '
  else
    html_tag.insert html_tag.index('>'), ' class="error"'
  end
end
```
to the `config/aplication.rb` file only an error tag is added to the label/input field (so we can style it red) and it doesn't mess up with the grid

**Comment by saradotlog** [comment]
Hey all! @GabrielleEaston @Timilehin08 @ncbui do you reckon http://localhost:3000/shifts page and http://localhost:3000/organizations/id should have the same styling?

**Comment by GabrielleEaston** [comment]
@saradotlog Now it looks very similar(buttons are styled differently). Do you think it's better if they look different? I am a bit confused, looked at too many alike pages in our App 😅

**Comment by saradotlog** [comment]
@GabrielleEaston I don't know, I was thinking that might be less confusing for the user if they are slightly different, but then they show the same, so it makes sense for them to be the same 😅😅 I'm a bit confused too as you can see 😂

**Comment by Timilehin08** [comment]
Hello @saradotlog @GabrielleEaston @ncbui It somehow skipped my mind to send this here. So sorry! I checked for the responsiveness of the app when we discussed this two weeks back and it's mobile responsive on different screens.

Here are a few screenshots of the different pages and it's responsiveness.
![Screen Shot 2021-04-28 at 18 34 13](https://user-images.githubusercontent.com/52857292/117221191-6425d000-adce-11eb-8116-3e9d8377ea42.png)
![Screen Shot 2021-04-28 at 18 02 00](https://user-images.githubusercontent.com/52857292/117221210-6a1bb100-adce-11eb-87d7-d72e14b5e4a4.png)
![Screen Shot 2021-04-28 at 17 58 58](https://user-images.githubusercontent.com/52857292/117221235-76a00980-adce-11eb-9664-96318a636dbc.png)
![Screen Shot 2021-04-28 at 17 55 32](https://user-images.githubusercontent.com/52857292/117221248-7bfd5400-adce-11eb-9c98-4f029f5e9efa.png)
![Screen Shot 2021-04-28 at 17 05 05](https://user-images.githubusercontent.com/52857292/117221274-87507f80-adce-11eb-88c8-29db7cf5f5a7.png)
![Screen Shot 2021-04-28 at 17 19 14](https://user-images.githubusercontent.com/52857292/117221282-8c153380-adce-11eb-89d2-bee29b423933.png)

**Comment by Timilehin08** [comment]
I don't think this pictures depict the responsiveness on all screens but we can be assured that the app is responsive on the various screens when i checked via inspect. We can check via inspect, developer tools to confirm when we can.

**Comment by GabrielleEaston** [comment]
Thank you @Timilehin08 for checking the responsiveness! ❤️

**Comment by ncbui** [comment]
This is great @Timilehin08 ! Thanks for working on this

**Comment by msarit** [comment]
Closing! 😄  Good job all!
