### ISSUE TITLE
Build Out UI for User Views

### ISSUE THREAD

**Issue by msarit** [OurTimeForTech/shiftwork2#11]
Breaking User UI Tasks Down:
- [ ] Task 1: Index, shows available shifts (renders on the Home page at the moment)
- [x] Task 2: Edit, allows editing password 
- [x] Task 3: New, Sign up for a new account view 
- [x] Task 4: Show view, the user is ether org or worker or has the option to create org/worker profile (Ready for QA)

_Breaking down by routes_

- http://localhost:3000/users/:id 
- http://localhost:3000/users/:id/edit

**Comment by ncbui** [comment]
Great implementation plans @GabrielleEaston. 
I'm leaning away from adding a list of users on http://localhost:3000/users/. With our MVP reduction, users don't have a reason to look through a list of users or workers.

**Comment by GabrielleEaston** [comment]
Okay! That makes sense! I will remove that route.
