### ISSUE TITLE
Build Out UI for Shift Views

### ISSUE THREAD

**Issue by msarit** [OurTimeForTech/shiftwork2#13]
Points of action:
- [x] 1. When navigating to http://localhost:3000/shifts/ the list of shifts appear. Styling
- [x] 2. If the one who navigates to the list of shifts is a worker, ability to drop the shift
- [x] 3. ~~Don't allow the worker to drop a shift if it starts in less than X hours.~~ (there is another issue for that) 
- [x] 4. http://localhost:3000/shifts/ – Organisations don't have permission to see the shifts they don't own. They can edit/delete the ones the own. They can add new shifts.

Questions: Will a user logged in as organisation have the permission to see all the shifts or just the ones they created? Would it make more sense to show the whole list only to workers? If so the shifts view for an organisation would look the same as their own list of shifts in their profile page. @GabrielleEaston @Timilehin08 @ncbui 

- [x] 5. Route localhost:3000/shifts/shift_id/edit already in place. If entered incorrect id 404 page shows. Needs styling
- [x] 6. Route http://localhost:3000/shifts/new already in place. Needs styling. 
- [x] 7. ~~Put view permissions in place (workers can't edit/create shifts, orgs can't edit shifts they don't own)~~  (created another issue for that)

**Comment by GabrielleEaston** [comment]
@saradotlog I think it makes sense to show the org only the shifts they created it. Workers can see the list of all the shifts and the list of upcoming shifts(shifts they filled).

**Comment by ncbui** [comment]
I agree, it makes sense to show the org only the shifts they own. Right now it looks like the '/shifts' and '/organizations/:id' views are essentially the same list. But the '/organizations/:id' page has a link to Create/Edit/Delete shifts. I wonder if there's more we can do to differentiate the two.

**Comment by Timilehin08** [comment]
I also agree and think it will make more sense to show the list to only the workers since I don’t think it’s in our MVP that Orgs can pick shifts even if they didn’t create them and workers are the ones that need to know the open or closed shifts. @saradotlog

**Comment by saradotlog** [comment]
hey! thank you all for your inputs! Maybe we can just allow to see the /shifts/ route to the ones logged as workers? and organizations don't have permission to see that part of the app, as it doesnt make sense for them. They will see theirs shifts on their profile page. 
And as @Timilehin08 said, if in the end we have time to add "nice to haves", we can grant them permission then.
