### ISSUE TITLE
Build Out UI for Worker Views

### ISSUE THREAD

**Issue by msarit** [OurTimeForTech/shiftwork2#14]
Breaking Worker’s UI Tasks Down: 

- [x] Step 1: Edit view `./workers/:id/edit`
- [x] Step 2: New view, `./workers/new`
- [x] Step 3: Show view, `./worker/:id,` if user is a worker owneractions (create, edit, delete) should be available
- [x] Step 4: Show view, `./worker/:id,` if user is not worker owner `./worker/:id` (create, edit, delete) not available

Workers should be able to view and put in availability but not allowed to drop a shift if it starts in less than X hours. Linked to #13

When user goes to /workers/:id, there is a list of all shifts available for the workers.
When user goes to /user/:id, users can create a new worker account or view existing worker’s account details. There is a link to edit the workers and a link to go to workers details page (which shows profile and shifts taken((availability of worker))

**Comment by Timilehin08** [comment]
@ncbui @GabrielleEaston 
I hope I’m not getting things mixed up but looking through the organization issue, is the index view now implemented? Or it was just for organization?

**Comment by Timilehin08** [comment]
Just to be sure please, we agreed that a worker can see other workers and shifts they picked right but can’t edit their details?
And not Only see organizations and available shifts? @saradotlog @ncbui @GabrielleEaston 
Also have I missed out on anything with the worker view details?

**Comment by ncbui** [comment]
We did talk about this, but now that I think about it maybe showing someone else's shift details might be a breach of privacy.

**Comment by ncbui** [comment]
Oops, sorry I missed your first comment. Your implementation plan looks good, it looks like the index for workers is also not implemented.  Could we revisit what workers can see about other workers?

**Comment by Timilehin08** [comment]
Hmm. Breach of privacy. I didn’t think of it that way. Oh the index view is also not implemented.
True about seeing only bios 🤔 . @GabrielleEaston @saradotlog what do we think?

**Comment by saradotlog** [comment]
Yeah, I think we need to review that. I don't really the point of workers seen a list of other workers? They can't really interact among them like in a social network. But if we do, I wouldn't show things like city, phone, email or personal details, neither shifts they have picked.

**Comment by saradotlog** [comment]
Also, even in social networks you have the option of making your profile private... or a bio empty. But in this case having the bio empty could be bad as organisations maybe would like to read a brief intro of the candidate... I'm thinking out loud

**Comment by GabrielleEaston** [comment]
@Timilehin08 I think I caught up with all the comments. I agree with everyone about the privacy concerns. If we want to show workers to each other, only name, maybe city and bio can be shown. Yes, it is not a good idea to show the picked-up shifts (too personal).

**Comment by msarit** [comment]
@Timilehin08 What is the status of the 4 tasks in this Issue, Timi? Thanks! 🙏🏾

**Comment by Timilehin08** [comment]
Oh yes@msarit I discussed the step 3 and 4 during the meeting with the team and @saradotlog agreed to cover. This was actually due to the network issues I had and I needed clarification on the authentication and since @saradotlog was doing something similar, she didn't mind doing it.

**Comment by msarit** [comment]
Okay that sounds good @Timilehin08

Please check off the items in the descriptions if they have been implemented; so we know when to close this issue once all items are checked 👍🏾

**Comment by Timilehin08** [comment]
It can be closed now @msarit. I just ticked it off now since it has all been implemented.
