### ISSUE TITLE
Prevent access to '/login' when user is signed in

### ISSUE THREAD

**Issue by msarit** [OurTimeForTech/shiftwork2#17]
Prevent access to '/login' when user is signed in.

Current process: 
When user navigates to /login, the new action for sessions is called. There is no logic in this action, so a login form is automatically rendered.

Implementation Options:
1. Adding a redirect to [sessions controller](https://pastebin.com/nzuVkMDf)
When the user navigates to /login, the router dispatches the `new` action for sessions. The `new` action redirects if the user logged in (and by default, renders new login form if user not logged in)
> def new
>   if logged_in?
>     return redirect_to index_path
>   end
> end

2. [Adding an action](https://guides.rubyonrails.org/routing.html#advanced-constraints) to the  /login path in `routes.rb`
When the user navigates to /login, the router dispatches the` check` action for sessions. The `check` action redirects if the user is logged in and dispatches the `new` action if they are not.
> get    '/login',   to: 'sessions#check'

> def check
>   if logged_in?
>     return redirect_to index_path (or where ever else we want to redirect)
>   else
>     return redirect_to user_login_path `TODO: How do I call an action from here?`
>   end
> end

**Comment by ncbui** [comment]
Thanks for merging @msarit Arit! Have closed the issue
