### ISSUE TITLE
Add time limit to when users can drop shifts

### ISSUE THREAD

**Issue by ncbui** [OurTimeForTech/shiftwork2#19]
Users should not be able to drop shifts that have already occurred or are set to start within X hours. 
Need to discuss exact details as a group.

**_Edit by Arit:_** I think a lead time of **24 hours** is enough for preventing workers from dropping a shift they've taken. This is what I'm implementing.

**Comment by msarit** [comment]
Thanks for creating this @ncbui. I'm holding off on adopting this issue until the JS-datetime-picker gem has been configured by @drippdropp

**Comment by msarit** [comment]
Leaving an update for this issue.

I have fixed the actual datetime-picker feature on the `shift_start` and `shift_end` fields 🎉 🎉 🎉 

Now I need to make sure that, while dates get saved in UTC timezone in the database, organizations can pick dates and times in their own timezone, and shifts' start and end times display in the user's own timezone 😅 

FYI none of these changes have been merged yet

@ncbui @GabrielleEaston @saradotlog @Timilehin08

**Comment by ncbui** [comment]
This is fantastic @msarit ! Thanks so much for implementing this!
