### ISSUE TITLE
Fix error in edit/new shift form

### ISSUE THREAD

**Issue by saradotlog** [OurTimeForTech/shiftwork2#41]
When editing or creating a new shift, the select shift status prompt an error when choosing the FILLED option:

<img width="1347" alt="create_shift_error" src="https://user-images.githubusercontent.com/2697750/115886885-ac99d100-a451-11eb-8870-b2c724d0a729.png">
<img width="1256" alt="edit_shift_error" src="https://user-images.githubusercontent.com/2697750/115886897-ae639480-a451-11eb-8dba-99b1c53c4a50.png">

**Comment by msarit** [comment]
@saradotlog I believe my latest commit fixed this issue, please check. If it is fixed, please update the issue label and close the issue 🙏🏾 

I believe the error came from the validation `validates :shift_open, presence: true` in the `shift.rb` model.

Apparently, in Rails, we do not validate booleans with the `presence` check, as Rails interprets the `false` boolean as `nonexistent` (https://medium.com/@mikeappell/rails-presence-validations-booleans-and-pain-1b04adb111ab).

I modified this validation to check for the presence of `true` or `false` in an array.

Tagging the rest of the team so everyone can read this comment: @GabrielleEaston @ncbui @Timilehin08
