### ISSUE TITLE
Bugs in Organization Show Page

### ISSUE THREAD

**Issue by msarit** [OurTimeForTech/shiftwork2#45]
In the organization#show page (http://localhost:3000/organization/:id), the user can still edit a Shift that is filled - that doesn't seem right to me. 🤷🏾‍♀️ 

Also, under the "Shift Worker" entry, "Worker Name" is hard-coded:
```ruby
<div class="col-7"><% unless shift.shift_open %>Worker Name<% end %></div>
```

This should be the actual worker's name.

---

### Definitions of Done
- [x] Hide shift's "Edit" link on the organization's card in the Org show page  (PR #69 )
- [x] Display the ACTUAL Worker's name on the organization's card (in progress)

**Comment by ncbui** [comment]
Step 2 blocked by #73
