### ISSUE TITLE
UI Add drop shift button

### ISSUE THREAD

**Issue by ncbui** [OurTimeForTech/shiftwork2#76]
Drop method already written into shift controller

- [ ] shift page
- [ ] worker's page

**Comment by saradotlog** [comment]
Hey @ncbui , I don't know if this is what you mean, but in the shifts page the drop button is already in place
<img width="823" alt="Screenshot 2021-04-30 at 18 08 37" src="https://user-images.githubusercontent.com/2697750/116722827-2f390800-a9df-11eb-8be5-b777ad96b360.png">

and in the workers page only needs the button styling, but there is also the link
<img width="607" alt="Screenshot 2021-04-30 at 18 09 53" src="https://user-images.githubusercontent.com/2697750/116722900-4841b900-a9df-11eb-8409-13c4411dc885.png">

I think @GabrielleEaston said she wants to make minor styling changes over the weekend, this might be one of them, just adding the btn-danger class. If not I don't mind to add it quickly

**Comment by GabrielleEaston** [comment]
@saradotlog Please add the class! I think with styling is better to add classes as we catch them! As long as @ncbui meant the styling.

**Comment by saradotlog** [comment]
@GabrielleEaston I saw it when adding the button class in the shifts form, but I wasnt sure I had to create a special PR for it 😂 😂 😂 
Ok, I'll add it now

**Comment by saradotlog** [comment]
That's a good idea. I already styled it, so I'm going to create a PR and add it as a tick box in that General view issue. Thanks!

**Comment by ncbui** [comment]
Thanks for catching this @saradotlog has the drop shift button recently been added? This is what I see when I am signed in aw a worker viewing their '/worker' page
<img width="461" alt="Screen Shot 2021-04-30 at 9 54 09 AM" src="https://user-images.githubusercontent.com/29789422/116727933-15290680-a99a-11eb-8851-7f1c588ea7cd.png">

**Comment by saradotlog** [comment]
Hmmm, no, i think it has been there a while but we can check the blame file.
Maybe you don't see it for the workers id change you made? Maybe your database now has the user id instead of the worker id associated to that shift and that's why you can't see it? 🤔

**Comment by GabrielleEaston** [comment]
I can see the drop button as well.
<img width="728" alt="Screen Shot 2021-04-30 at 12 56 53 PM" src="https://user-images.githubusercontent.com/48966654/116730363-6b0ba780-a9b6-11eb-9492-7b0850ab3f90.png">

**Comment by ncbui** [comment]
Thanks for helping to troubleshoot this. This is what I'm now seeing on the worker page after signing up for a new shift. Have made sure I pulled the latest from upstream, updated yarn and ran bundle install. How do I check the blame file?
<img width="1402" alt="Screen Shot 2021-04-30 at 10 30 14 AM" src="https://user-images.githubusercontent.com/29789422/116731867-21639280-a99f-11eb-92c1-6dc2d6caf2d8.png">

**Comment by GabrielleEaston** [comment]
@ncbui I am on the main branch (it is updated). So weird, I can see the drop button if I signed it as a worker. I tested dropping shifts, taking new ones and the drop button is there. I am very curious to know what Is happening😅

<img width="1400" alt="Screen Shot 2021-04-30 at 2 02 24 PM" src="https://user-images.githubusercontent.com/48966654/116735795-0273f900-a9bd-11eb-9eb7-955c11a000a9.png">

**Comment by saradotlog** [comment]
Then @ncbui try to reset the dB and try again? It's the only thing I can think of

**Comment by GabrielleEaston** [comment]
@ncbui If resetting DB doesn't help, try to reset your main branch  ```git reset --hard upstream/main```
Not sure if it's a good practice, I've used this command a few times.

**Comment by ncbui** [comment]
Feature already exists. @saradotlog @GabrielleEaston  thanks for your help with this! Closing now.
